development:
  adapter: postgresql
  database: feedback 
  pool: 5
  timeout: 5000
  min_messages: WARNING

test:
  adapter: postgresql
  database: feedback_test
  pool: 5
  timeout: 5000
  min_messages: WARNING


